<?php

namespace controller;

use ControllerScheme;
use FwConnection;
use FwHtml\Elements\Tags\Main\HtmlTags;
use model\Entity\CustomersEntity;

class InquiryCustomer extends ControllerScheme
{
    const name = 'استعلام مشتری';

    public function getFileDetails()
    {
        $creditId = $_POST['creditId'];

        var_dump($creditId);
//        $data = $this->model()::get($creditId);
//        $output = [
//            'requested'=>$data->credit_file_requested_credit ,
//            'refund'=>$data->credit_file_refund ,
//            'monthly'=>$data->credit_file_monthly_profit ,
//            'amount'=>$data->credit_file_payment_amount ,
//            'check'=>$data->credit_file_guaranteed_check ,
//            'filenumber'=>$data->credit_file_filenumber ,
//
//        ];

//        return json_encode($output,JSON_UNESCAPED_UNICODE);

    }
//    public function main()
//    {
//
//        if ($this->requestArray()['id'] > 0){
//            var_dump($_POST['id']);
//
//            return $this->view($this->viewName(), 'main', [
//                $this->model()->getAllFiltered('customer_id', 1)
//            ]);
//
//
//        }
//
//        return parent::main(); // TODO: Change the autogenerated stub
//    }
}